// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var app;

  app = angular.module('chatBotApp', ['fsm']);

  app.config([
    'FsmProvider', function(FsmProvider) {
      return FsmProvider.config({
        test: "test"
      });
    }
  ]);

}).call(this);

//# sourceMappingURL=app.map
