// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  angular.module('chatBotApp').controller('MainCtrl', [
    '$scope', function($scope) {
      return $scope.title = "Hello FSM, I am bot.";
    }
  ]);

}).call(this);

//# sourceMappingURL=main.map
